# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip wheel .
  displayName: 'Build packages'
  
- task: TwineAuthenticate@0
  inputs:
    artifactFeeds: 'wheels'
  displayName: 'Twine authentication'
  
- script: |
    pip install twine
    twine upload -r "wheels" --config-file $(PYPIRC_PATH) dist/*.whl
  displayName: 'Upload artifacts'
